"""Attribute reason added to expenseItem

Revision ID: 4456f3e07348
Revises: efb6d6ea4841
Create Date: 2024-12-29 19:12:16.275941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4456f3e07348'
down_revision: Union[str, None] = 'efb6d6ea4841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenseitem', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenseitem', 'reason')
    # ### end Alembic commands ###
