"""User attributes fix due to implementation of roles

Revision ID: 61b419d7bcc9
Revises: 4456f3e07348
Create Date: 2024-12-31 15:37:32.241144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '61b419d7bcc9'
down_revision: Union[str, None] = '4456f3e07348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'title')
    op.drop_column('user', 'isRealEstate')
    op.drop_column('user', 'isOwner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isOwner', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('isRealEstate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
