"""Relationship fix

Revision ID: efb6d6ea4841
Revises: 
Create Date: 2024-12-29 00:52:02.695078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efb6d6ea4841'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('tenantId', sa.Integer(), nullable=True))
    op.drop_constraint('flat_ibfk_1', 'flat', type_='foreignkey')
    op.create_foreign_key(None, 'flat', 'user', ['tenantId'], ['id'])
    op.drop_column('flat', 'ownerId')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.drop_column('user', 'flatTenantId')
    op.drop_column('user', 'flatId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('flatId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('flatTenantId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_2', 'user', 'flat', ['flatId'], ['id'])
    op.create_foreign_key('user_ibfk_1', 'user', 'flat', ['flatTenantId'], ['id'])
    op.add_column('flat', sa.Column('ownerId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flat', type_='foreignkey')
    op.create_foreign_key('flat_ibfk_1', 'flat', 'user', ['ownerId'], ['id'])
    op.drop_column('flat', 'tenantId')
    # ### end Alembic commands ###
